# -*- coding: utf-8 -*-
# @Author: ZYSama
# @Created Date: 2019-10-30 22:53:15
# @Last Modified time: 2019-11-04 16:15:20
# @Software: Sublime
from ntrusign import *
import time
import numpy as np



if __name__ == '__main__':
	#Bob
	print "Bob Will Generate his Public Key using Parameters"
	print "N=7,p=2 and q=491531"
	Bob = NTRUSign(7,2,491531)
	f=[1,0,-1,1,-1,1]
	g=[-1,0,1,1,1,0,-1]

	d=2
	print "f(x)= ",f
	print "g(x)= ",g
	print "d   = ",d
	Bob.genPublicKey(f,g,2)
	pub_key=Bob.getPublicKey()
	print "Public Key Generated by Bob: ",pub_key
	print "-------------------------------------------------"

	#Alice
	Alice=NTRUSign(7,2,491531)
	Alice.setPublicKey(pub_key)
	# msg=[1,0,1,0,1,1,1]
	msg = 'fsdfsdf'
	print "Alice's Original Message to be signed   : ",msg
	ranPol=[-1,-1,1,1]
	print "Alice's Random Polynomial  : ",ranPol
	b = np.random.randint(0,2)
	print "b:,",b
	sign = Alice.sign(msg,ranPol,b,f,g,2)
	print "signature is :",sign
	print "-------------------------------------------------"

	#Bob
	print "Bob verify signature"
	Bob.verify(msg,sign)




